name: Update Node-FFmpeg Image

on:
    schedule:
        # 每天凌晨3点运行
        - cron: "0 3 * * *"
    workflow_dispatch: # 允许手动触发

jobs:
    check-and-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Check for FFmpeg image updates
              id: check_updates
              run: |
                  # 获取当前的镜像摘要  
                  CURRENT_DIGEST=$(docker manifest inspect jrottenberg/ffmpeg:7.1-ubuntu2204 | jq -r '.digest')  
                  echo "Current digest: $CURRENT_DIGEST"  

                  # 获取上次构建的摘要（如果存在）  
                  if [ -f last_digest.txt ]; then  
                    LAST_DIGEST=$(cat last_digest.txt)  
                    echo "Last digest: $LAST_DIGEST"  
                  else  
                    LAST_DIGEST=""  
                    echo "No previous digest found"  
                  fi  

                  # 比较摘要  
                  if [ "$CURRENT_DIGEST" != "$LAST_DIGEST" ]; then  
                    echo "Image updated, need to rebuild"  
                    echo "REBUILD=true" >> $GITHUB_OUTPUT  
                    echo "$CURRENT_DIGEST" > last_digest.txt  
                  else  
                    echo "No changes detected"  
                    echo "REBUILD=false" >> $GITHUB_OUTPUT  
                  fi

            - name: Build ffmpeg-7.1-ubuntu2404-node22 image
              if: steps.check_updates.outputs.REBUILD == 'true'
              uses: docker/build-push-action@v4
              with:
                  context: ./images/ffmpeg-7.1-ubuntu2404/node22
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/node-ffmpeg:latest  
                      ${{ secrets.DOCKERHUB_USERNAME }}/node-ffmpeg:7.1-ubuntu2404-node22
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Commit and push last digest
              if: steps.check_updates.outputs.REBUILD == 'true'
              run: |
                  git config --global user.name 'GitHub Actions'  
                  git config --global user.email 'actions@github.com'  
                  git add last_digest.txt  
                  git commit -m "Update last digest" || echo "No changes to commit"  
                  git push
